In [9]:
%pip install pandas

Requirement already satisfied: pandas in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
df = pd.read_csv('raw_data.csv')
df

    id          name   age    country   gender
0    1      John Doe  29.0        USA     Male
1    1      John Doe  29.0        USA     Male
2    2    Jane Smith   NaN     Canada   Female
3    3          Alex   NaN        USA  Unknown
4    4  Maria Garcia  34.0      Spain   Female
5    5        Li Wei  27.0      China     Male
6    6           NaN  45.0      India   Female
7    7    Ahmed Khan  38.0        NaN     Male
8    8      Sara Ali  31.0        UAE   Female
9    9    Noah Brown   NaN         UK     Male
10  10   Emma Wilson  26.0  Australia   Female

In [11]:
df.isnull()

       id   name    age  country  gender
0   False  False  False    False   False
1   False  False  False    False   False
2   False  False   True    False   False
3   False  False   True    False   False
4   False  False  False    False   False
5   False  False  False    False   False
6   False   True  False    False   False
7   False  False  False     True   False
8   False  False  False    False   False
9   False  False   True    False   False
10  False  False  False    False   False

In [12]:
df.dropna() # drops all the rows with null values
#df.dropna(inplace=True) # drops all the rows with null values and updates the dataframe
df.dropna(axis=1) # drops all the columns with null values

    id   gender
0    1     Male
1    1     Male
2    2   Female
3    3  Unknown
4    4   Female
5    5     Male
6    6   Female
7    7     Male
8    8   Female
9    9     Male
10  10   Female

In [13]:
df["age"].fillna(df["age"].mean()) # fills the null values in the age column with the mean of the age column

0     29.000
1     29.000
2     32.375
3     32.375
4     34.000
5     27.000
6     45.000
7     38.000
8     31.000
9     32.375
10    26.000
Name: age, dtype: float64

In [16]:
cleaned_data = df.copy() # creates a copy of the dataframe
age_mean = cleaned_data["age"].mean() # calculates the mean of the age column
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean) # fills the null values in the age column with the mean of the age column and updates the dataframe
cleaned_data

    id          name     age    country   gender
0    1      John Doe  29.000        USA     Male
1    1      John Doe  29.000        USA     Male
2    2    Jane Smith  32.375     Canada   Female
3    3          Alex  32.375        USA  Unknown
4    4  Maria Garcia  34.000      Spain   Female
5    5        Li Wei  27.000      China     Male
6    6           NaN  45.000      India   Female
7    7    Ahmed Khan  38.000        NaN     Male
8    8      Sara Ali  31.000        UAE   Female
9    9    Noah Brown  32.375         UK     Male
10  10   Emma Wilson  26.000  Australia   Female

In [24]:
#handle duplicates
df[["country", "gender"]].duplicated() # returns a boolean series indicating whether each value in the country column is a duplicate or not
df2 = df.copy()
df2.drop_duplicates(inplace=True) # drops all the duplicate rows and updates the dataframe

In [27]:
#add income column
df2["income"] = [60000, 40000, 50000, 70000, 30000, 80000, 90000, 20000, 10000, 110000]

In [43]:
#feature engineering
df2["tax"] = df2["income"].apply(lambda x: "20%" if x > 50000 else "10%") # creates a new column called tax and fills it with 20% if the income is greater than 50000 and 10% otherwise
df2

,id,name,age,country,gender,income,tax,gender_clean,gender_code
0,1,John Doe,29.0,USA,NaN,60000,20%,Unknown,U
2,2,Jane Smith,NaN,Canada,NaN,40000,10%,Unknown,U
3,3,Alex,NaN,USA,NaN,50000,10%,Unknown,U
4,4,Maria Garcia,34.0,Spain,NaN,70000,20%,Unknown,U
5,5,Li Wei,27.0,China,NaN,30000,10%,Unknown,U
6,6,NaN,45.0,India,NaN,80000,20%,Unknown,U
7,7,Ahmed Khan,38.0,NaN,NaN,90000,20%,Unknown,U
8,8,Sara Ali,31.0,UAE,NaN,20000,10%,Unknown,U
9,9,Noah Brown,NaN,UK,NaN,10000,10%,Unknown,U
10,10,Emma Wilson,26.0,Australia,NaN,110000,20%,Unknown,U

In [44]:
gender_map = { "Male": "M", "Female": "F", "Unknown": "U" }
df2["gender"] = df2["gender"].map(gender_map) # maps the values in the gender column
df2

,id,name,age,country,gender,income,tax,gender_clean,gender_code
0,1,John Doe,29.0,USA,NaN,60000,20%,Unknown,U
2,2,Jane Smith,NaN,Canada,NaN,40000,10%,Unknown,U
3,3,Alex,NaN,USA,NaN,50000,10%,Unknown,U
4,4,Maria Garcia,34.0,Spain,NaN,70000,20%,Unknown,U
5,5,Li Wei,27.0,China,NaN,30000,10%,Unknown,U
6,6,NaN,45.0,India,NaN,80000,20%,Unknown,U
7,7,Ahmed Khan,38.0,NaN,NaN,90000,20%,Unknown,U
8,8,Sara Ali,31.0,UAE,NaN,20000,10%,Unknown,U
9,9,Noah Brown,NaN,UK,NaN,10000,10%,Unknown,U
10,10,Emma Wilson,26.0,Australia,NaN,110000,20%,Unknown,U