In [2]:
%pip install requests

Requirement already satisfied: requests in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/raghav/.local/lib/python3.14/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from requests) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import requests

In [8]:
url = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(url)
res

In [9]:
data = res.json()

In [14]:
import pandas as pd
df = pd.json_normalize(data["data"])
df = df[["id","Title"]]

In [15]:
df

    id          Title
0    1         Carrie
1    2    Salem's Lot
2    3    The Shining
3    4           Rage
4    5      The Stand
..  ..            ...
58  59   The Outsider
59  60      Elevation
60  61  The Institute
61  62          Later
62  63  Billy Summers

[63 rows x 2 columns]

In [17]:
url2 = "https://cataas.com/api/cats?tags=cute"
res2 = requests.get(url2)
res2

In [19]:
json_data = res2.json()
json_data

[{'id': '0F0IKAPOdWiE755P',
  'tags': ['meet', 'cute'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-06-18T09:46:45.702Z'},
 {'id': '0GC9MRUAqxhBzPyA',
  'tags': ['cute'],
  'mimetype': 'image/png',
  'createdAt': '2024-09-15T15:45:25.375Z'},
 {'id': '0mstmOIucwiN80jb',
  'tags': ['cute', 'black'],
  'mimetype': 'image/jpeg',
  'createdAt': '2023-10-25T00:04:03.771Z'},
 {'id': '0RU7ZkgzyvWv8UJG',
  'tags': ['tuxedo', 'computer', 'sleepy', 'cute', 'sleeping'],
  'mimetype': 'image/png',
  'createdAt': '2024-04-20T22:52:58.132Z'},
 {'id': '0ztFbDrgDV2K7yJ1',
  'tags': ['cute', 'orange', 'funny', 'lasagna', 'garfield'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-08-23T20:15:26.393Z'},
 {'id': '1bJraW0IwSPm3MVd',
  'tags': ['cute', 'fluffy'],
  'mimetype': 'image/jpeg',
  'createdAt': '2022-04-27T01:49:50.792Z'},
 {'id': '1CF7xZmlX0t8QpgP',
  'tags': ['ange', 'cute'],
  'mimetype': 'image/jpeg',
  'createdAt': '2016-11-22T05:38:06.656Z'},
 {'id': '1DrcyohjhwcNaRIz',
  'tags': ['cute', 'orange', 'sleepy', 'tired', 'outside', 'grass'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-02-29T00:49:57.420Z'},
 {'id': '1KeQpy7eHqi0SFmc',
  'tags': ['orange', 'cute', 'lying', 'bed', 'blanket'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-10-08T23:54:00.959Z'},
 {'id': '1N2AH31jiY6N9TYc',
  'tags': ['cute', 'mlem'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-02-08T07:59:29.085Z'}]

In [20]:
df = pd.json_normalize(json_data)
df

,id,tags,mimetype,createdAt
0,0F0IKAPOdWiE755P,"[meet, cute]",image/jpeg,2024-06-18T09:46:45.702Z
1,0GC9MRUAqxhBzPyA,[cute],image/png,2024-09-15T15:45:25.375Z
2,0mstmOIucwiN80jb,"[cute, black]",image/jpeg,2023-10-25T00:04:03.771Z
3,0RU7ZkgzyvWv8UJG,"[tuxedo, computer, sleepy, cute, sleeping]",image/png,2024-04-20T22:52:58.132Z
4,0ztFbDrgDV2K7yJ1,"[cute, orange, funny, lasagna, garfield]",image/jpeg,2024-08-23T20:15:26.393Z
5,1bJraW0IwSPm3MVd,"[cute, fluffy]",image/jpeg,2022-04-27T01:49:50.792Z
6,1CF7xZmlX0t8QpgP,"[ange, cute]",image/jpeg,2016-11-22T05:38:06.656Z
7,1DrcyohjhwcNaRIz,"[cute, orange, sleepy, tired, outside, grass]",image/jpeg,2024-02-29T00:49:57.420Z
8,1KeQpy7eHqi0SFmc,"[orange, cute, lying, bed, blanket]",image/jpeg,2024-10-08T23:54:00.959Z
9,1N2AH31jiY6N9TYc,"[cute, mlem]",image/jpeg,2024-02-08T07:59:29.085Z