In [3]:
!pip install pandas

Requirement already satisfied: pandas in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/raghav/.conda/envs/primeenv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
info = {
    "Names": ["Raghav", "Sonia", "Amit"],
    "Ages": [25, 30, 22],
    "Cities": ["Delhi", "Mumbai", "Bangalore"]
}
df = pd.DataFrame(info)
print(df)

    Names  Ages     Cities
0  Raghav    25      Delhi
1   Sonia    30     Mumbai
2    Amit    22  Bangalore

In [5]:
df

    Names  Ages     Cities
0  Raghav    25      Delhi
1   Sonia    30     Mumbai
2    Amit    22  Bangalore

## EDA(EXPLORATORY DATA ANALYSIS)
 - load and structure data and understand
 - clean the data
 - statistical summary
 - visualization

In [6]:
s = pd.Series([10, 20, 30, 40, 50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
s = pd.Series([10, 20, 30, 40, 50], index=['adam', 'bie', 'charlie', 'david', 'eve'])
print(s)

adam       10
bie        20
charlie    30
david      40
eve        50
dtype: int64

In [8]:
#vectorized operations
s = pd.Series([10, 20, 30, 40, 50])
print(s * 2) #multiply each element by 2
print(s + 5) #add 5 to each element
print(s / 10) #divide each element by 10

0     20
1     40
2     60
3     80
4    100
dtype: int64
0    15
1    25
2    35
3    45
4    55
dtype: int64
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [9]:
s1 = pd.Series([1, 2, 3, 4, 5])
s1[0] = 10
print(s1)

0    10
1     2
2     3
3     4
4     5
dtype: int64

In [10]:
changed_s1 = s1.drop(0) #drop the first element
print(changed_s1)

1    2
2    3
3    4
4    5
dtype: int64

In [11]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}
d = pd.DataFrame(data)
print(d)
print (d["Name"]) #access the "Name" column
print (d["Age"]) #access the "Age" column
print (d["City"]) #access the "City" column
print(d, type(d))
print(d.index)
print(d.columns)
print(d.values)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
0    25
1    30
2    35
Name: Age, dtype: int64
0       New York
1    Los Angeles
2        Chicago
Name: City, dtype: str
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'City'], dtype='str')
[['Alice' 25 'New York']
 ['Bob' 30 'Los Angeles']
 ['Charlie' 35 'Chicago']]

In [12]:
#csv data reading
df = pd.read_csv('employee_data.csv')
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10     Jane   30    Finance   60000

In [13]:
#json data reading
df_json = pd.read_json('employee_data.json')
print(df_json)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10     Jane   30    Finance   60000

In [14]:
#methods
print(df.head()) #first 5 rows
print(df.tail()) #last 5 rows
print(df.info()) #summary of the DataFrame

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10    Jane   30    Finance   60000
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes
None

In [15]:
print(df.describe()) #statistical summary of numerical columns

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [16]:
df_new = pd.read_csv('globalAirQuality.csv')
# print(df_new.head())
df_new.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [17]:
#selecting data
df_new["city"] #selecting a single column

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [18]:
df_new[["city", "country"]] #selecting multiple columns

           city country
0      New York      US
1      New York      US
2      New York      US
3      New York      US
4      New York      US
...         ...     ...
17995    Zurich      CH
17996    Zurich      CH
17997    Zurich      CH
17998    Zurich      CH
17999    Zurich      CH

[18000 rows x 2 columns]

In [19]:
df_new.iloc[0] #selecting the first row

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [20]:
df_new.iloc[0:5] #selecting the first 5 rows startIdx: 0, endIndex: 5

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [21]:
df_new[df_new["city"] == "Delhi"] #selecting rows where city is Delhi

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6840,2025-11-04 18:25:17.554219,IN,Delhi,28.704,77.102,44.829,28.334,9.180,6.874,49.548,0.911,89,33.540,40.150,7.473
6841,2025-11-04 19:25:17.554219,IN,Delhi,28.704,77.102,38.797,54.046,53.594,3.407,40.532,0.454,133,23.468,30.788,2.936
6842,2025-11-04 20:25:17.554219,IN,Delhi,28.704,77.102,54.364,131.193,34.506,3.664,48.325,1.211,131,16.154,55.117,2.934
6843,2025-11-04 21:25:17.554219,IN,Delhi,28.704,77.102,26.080,61.262,8.017,6.116,47.416,0.908,61,35.881,86.602,6.232
6844,2025-11-04 22:25:17.554219,IN,Delhi,28.704,77.102,18.285,54.259,43.646,6.036,47.786,0.409,109,37.776,55.852,6.343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7195,2025-11-19 13:25:17.554219,IN,Delhi,28.704,77.102,16.101,19.223,57.290,7.124,63.720,0.568,143,11.819,80.977,4.030
7196,2025-11-19 14:25:17.554219,IN,Delhi,28.704,77.102,48.989,68.555,25.099,7.108,38.624,0.712,97,21.355,41.076,9.402
7197,2025-11-19 15:25:17.554219,IN,Delhi,28.704,77.102,37.461,14.375,25.422,8.830,48.149,0.469,74,37.608,43.422,1.466
7198,2025-11-19 16:25:17.554219,IN,Delhi,28.704,77.102,77.418,121.415,0.139,7.561,47.000,0.845,154,27.715,80.107,7.530
7199,2025-11-19 17:25:17.554219,IN,Delhi,28.704,77.102,62.481,87.965,13.657,2.311,63.675,0.800,124,12.333,86.384,1.656

## Loc vs iLoc
| Feature         | `loc`              | `iloc`                        |
| --------------- | ------------------ | ----------------------------- |
| Based on        | **Labels (names)** | **Positions (index numbers)** |
| Works with      | Row/column names   | Integer positions             |
| Slice behavior  | **Inclusive**      | **Exclusive (like Python)**   |
| Accepts boolean | ✅ Yes              | ✅ Yes                         |

In [22]:
df_new.loc[0:5, ["city", "country"]] #selecting first 5 rows and specific columns using loc

       city country
0  New York      US
1  New York      US
2  New York      US
3  New York      US
4  New York      US
5  New York      US

In [23]:
df_new.iloc[0:3,1:5]   #selecting first 3 rows and columns from index 1 to 4 using iloc

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [24]:
df_new.at[0, "city"] #selecting a single value using at

'New York'

In [25]:
df_new.iat[0, 2] #selecting a single value using iat where i is integer position

'New York'

In [26]:
cities = df_new["city"].copy() #copying the "city" column to a new variable
print(cities)
cities[0] = "New Delhi" #modifying the first element of the copied series
print(cities) #printing the modified series
print(df_new["city"]) #printing the original "city" column to show it is unchanged

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str
0        New Delhi
1         New York
2         New York
3         New York
4         New York
           ...
17995       Zurich
17996       Zurich
17997       Zurich
17998       Zurich
17999       Zurich
Name: city, Length: 18000, dtype: str
0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [27]:
#filtering data
df = pd.read_csv('globalAirQuality.csv')

In [28]:
df[df["aqi"] > 100] #filtering rows where aqi is greater than 100

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [29]:
df[(df["aqi"] > 100) & (df["city"] == "Delhi")] #filtering rows where aqi is greater than 100 and city is Delhi

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6841,2025-11-04 19:25:17.554219,IN,Delhi,28.704,77.102,38.797,54.046,53.594,3.407,40.532,0.454,133,23.468,30.788,2.936
6842,2025-11-04 20:25:17.554219,IN,Delhi,28.704,77.102,54.364,131.193,34.506,3.664,48.325,1.211,131,16.154,55.117,2.934
6844,2025-11-04 22:25:17.554219,IN,Delhi,28.704,77.102,18.285,54.259,43.646,6.036,47.786,0.409,109,37.776,55.852,6.343
6846,2025-11-05 00:25:17.554219,IN,Delhi,28.704,77.102,44.197,52.547,49.678,3.790,38.681,0.716,124,19.959,38.100,2.399
6848,2025-11-05 02:25:17.554219,IN,Delhi,28.704,77.102,55.419,71.821,25.697,9.105,28.735,0.854,110,19.464,87.713,6.822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7189,2025-11-19 07:25:17.554219,IN,Delhi,28.704,77.102,68.489,93.276,28.489,3.812,56.915,1.275,136,19.881,60.224,0.600
7193,2025-11-19 11:25:17.554219,IN,Delhi,28.704,77.102,35.366,48.881,42.376,4.024,43.475,0.931,105,23.226,42.734,2.272
7195,2025-11-19 13:25:17.554219,IN,Delhi,28.704,77.102,16.101,19.223,57.290,7.124,63.720,0.568,143,11.819,80.977,4.030
7198,2025-11-19 16:25:17.554219,IN,Delhi,28.704,77.102,77.418,121.415,0.139,7.561,47.000,0.845,154,27.715,80.107,7.530
7199,2025-11-19 17:25:17.554219,IN,Delhi,28.704,77.102,62.481,87.965,13.657,2.311,63.675,0.800,124,12.333,86.384,1.656

In [ ]:
# query method - returns copy of original data
aqi_val = 100
df.query("aqi>100 & temperature>30")[['city', 'country']]
df.query("aqi > @aqi_val & temperature>30")[['city', 'country']]

           city country
6      New York      US
7      New York      US
14     New York      US
17     New York      US
25     New York      US
...         ...     ...
17947    Zurich      CH
17950    Zurich      CH
17975    Zurich      CH
17976    Zurich      CH
17991    Zurich      CH

[2384 rows x 2 columns]